name: flutter_soundfork
version: 1.0.0
description: 'A complete API for audio playback and recording. Audio player, audio recorder.'
homepage: https://github.com/mideind/flutter_soundfork
repository: https://github.com/mideind/flutter_soundfork

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=2.0.0"

dependencies:
  path_provider: ^2.0.2
  recase: ^4.0.0
  uuid: ^3.0.1
  provider: ^6.0.0
  path: ^1.8.0
  synchronized: ^3.0.0
  logger: "^2.0.1"
  flutter:
    sdk: flutter
# ============================================================================
  flutter_soundfork_platform_interface:
    path: ../flutter_soundfork_platform_interface # Flutter Sound Dir
# ============================================================================

dev_dependencies:
  pedantic: ^1.11.0


# For information on the generic Dart part of this file, see the
# following page: https:/www/flutter-sound.canardoux.xyz/doc.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: is.mideind.fluttersoundfork
        pluginClass: FlutterSound
      ios:
        pluginClass: FlutterSound


  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.io/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.io/custom-fonts/#from-packages
